version: '3.8'

services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUDA_VERSION: 12.1.0
        CUDNN_VERSION: 8
        UBUNTU_VERSION: 22.04
        PYTHON_VERSION: 3.11
        COMFYUI_COMMIT: master
    image: mycomfyui:latest
    container_name: comfyui
    hostname: comfyui
    runtime: nvidia
    
    environment:
      # NVIDIA settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Memory optimization
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - CUDA_LAUNCH_BLOCKING=0
      - CUDNN_BENCHMARK=1
      
    ports:
      - "8188:8188"
      
    volumes:
      # Models - preserves your nested folder structure
      - ${MODELS_PATH:-./models}:/app/models
      # Input/Output directories
      - ${OUTPUT_PATH:-./output}:/app/output
      - ${INPUT_PATH:-./input}:/app/input
      # User data
      - ./user:/app/user
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 32G  # Adjust based on your system
          
    restart: unless-stopped
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  default:
    name: comfyui-network
    driver: bridge 